backend:
  # Change this to latest-camera to enable the camera feature flag.
  # Alternatively, set ROSHAMBO_ENABLE_CAMERA=true in the environment
  # for the backend deployment while still using the latest tag.
  image: quay.io/rhdevelopers/roshambo-backend:sha-4a5692d
  # Do not change. Backend is not designed to scale horizontally.
  repicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "2"
frontend:
  image: quay.io/rhdevelopers/roshambo-frontend:latest
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
